export type Lang = 'fr' | 'en'

export function getLang(): Lang {
  return (localStorage.getItem('bmt_lang') || 'fr') as Lang
}

export const MAP_T = {
  fr: {
    toolDraw:    '● Tracer',
    toolEraser:  '✕ Gomme',
    toolBusstop: '🚏 Arrêt',
    toolStation: '🏢 Station',
    titleDraw:   'Tracer une ligne',
    titleErase:  'Effacer',
    titleBusstop:'Arrêt de bus',
    titleStation:'Station',
    titleReset:  'Réinitialiser le dessin',
    titleTools:  'Outils',
    titleResults:'Carte citoyenne',
    titleFinish: 'Terminer',
    next:        'Suivant',
    confirmReset:'Effacer tous les tracés et recommencer à zéro ?',
    draftRestored:(lines: number, stops: number) =>
      `Brouillon restauré — ${lines} ligne${lines !== 1 ? 's' : ''}${stops > 0 ? `, ${stops} arrêt${stops !== 1 ? 's' : ''}` : ''}`,
    hintStart:   'Appuyez sur la carte pour commencer une ligne',
    hintDraw:    'Appuyez pour ajouter des points',
    statLine:    (n: number) => `${n} ligne${n !== 1 ? 's' : ''}`,
    statStop:    (n: number) => `${n} arrêt${n !== 1 ? 's' : ''}`,
    statStation: (n: number) => `${n} station${n !== 1 ? 's' : ''}`,
    modalTypeBusstop: 'Arrêt de bus',
    modalTypeStation: 'Station / Gare',
    modalTypeEnBusstop: 'Bus stop',
    modalTypeEnStation: 'Station',
    modalPlaceholderBusstop: 'ex: Arrêt Main St.',
    modalPlaceholderStation: 'ex: Gare Moncton',
    modalHintSnap:   (type: 'busstop' | 'station') =>
      type === 'busstop'
        ? "L'arrêt se colle sur votre ligne — déplacez la carte pour choisir l'emplacement exact"
        : "La station se colle sur votre ligne — déplacez la carte pour choisir l'emplacement exact",
    modalHintFree:   (type: 'busstop' | 'station') =>
      type === 'busstop'
        ? "Déplacez la carte pour positionner l'arrêt"
        : "Déplacez la carte pour positionner la station",
    modalCancel:  'Annuler',
    modalConfirm: 'Confirmer',
    modalLabel:   'Nom (optionnel)',
  },
  en: {
    toolDraw:    '● Draw',
    toolEraser:  '✕ Erase',
    toolBusstop: '🚏 Stop',
    toolStation: '🏢 Station',
    titleDraw:   'Draw a line',
    titleErase:  'Erase',
    titleBusstop:'Bus stop',
    titleStation:'Station',
    titleReset:  'Reset drawing',
    titleTools:  'Tools',
    titleResults:'Citizen map',
    titleFinish: 'Finish',
    next:        'Next',
    confirmReset:'Clear all drawings and start over?',
    draftRestored:(lines: number, stops: number) =>
      `Draft restored — ${lines} line${lines !== 1 ? 's' : ''}${stops > 0 ? `, ${stops} stop${stops !== 1 ? 's' : ''}` : ''}`,
    hintStart:   'Tap the map to start drawing a line',
    hintDraw:    'Tap to add points',
    statLine:    (n: number) => `${n} line${n !== 1 ? 's' : ''}`,
    statStop:    (n: number) => `${n} stop${n !== 1 ? 's' : ''}`,
    statStation: (n: number) => `${n} station${n !== 1 ? 's' : ''}`,
    modalTypeBusstop: 'Bus stop',
    modalTypeStation: 'Station / Hub',
    modalTypeEnBusstop: 'Arrêt',
    modalTypeEnStation: 'Station',
    modalPlaceholderBusstop: 'e.g. Main St. Stop',
    modalPlaceholderStation: 'e.g. Moncton Station',
    modalHintSnap:   (type: 'busstop' | 'station') =>
      type === 'busstop'
        ? 'The stop snaps to your line — move the map to choose the exact position'
        : 'The station snaps to your line — move the map to choose the exact position',
    modalHintFree:   (type: 'busstop' | 'station') =>
      type === 'busstop'
        ? 'Move the map to position the stop'
        : 'Move the map to position the station',
    modalCancel:  'Cancel',
    modalConfirm: 'Confirm',
    modalLabel:   'Name (optional)',
  },
}

export const FORM_T = {
  fr: {
    title:        'Vos informations',
    subtitle:     'Your information',
    required:     'Requis',
    emailInvalid: 'Courriel invalide',
    successTitle: 'Merci !',
    successMsg:   'Votre suggestion a bien été reçue.',
    successMsgAlt:'Thank you! Your suggestion has been received.',
    viewMap:      'Voir la carte citoyenne →',
    backMap:      '← Retour à la carte',
    send:         'Envoyer / Send',
    labelNom:     'Nom',
    labelNomSub:  'Last name',
    labelPrenom:  'Prénom',
    labelPrenomSub:'First name',
    labelAdresse: 'Adresse',
    labelAdresseSub:'Address',
    labelEmail:   'Courriel',
    labelEmailSub:'Email',
    labelSuggestion:'Suggestion',
    labelSuggestionSub:'Suggestion',
    placeholderSuggestion:'Décrivez votre suggestion de ligne de bus… / Describe your bus route suggestion…',
    saveError:    "Impossible d'envoyer vos informations — vérifiez votre connexion et réessayez.",
  },
  en: {
    title:        'Your information',
    subtitle:     'Vos informations',
    required:     'Required',
    emailInvalid: 'Invalid email',
    successTitle: 'Thank you!',
    successMsg:   'Your suggestion has been received.',
    successMsgAlt:'Merci ! Votre suggestion a bien été reçue.',
    viewMap:      'View the citizen map →',
    backMap:      '← Back to map',
    send:         'Send / Envoyer',
    labelNom:     'Last name',
    labelNomSub:  'Nom',
    labelPrenom:  'First name',
    labelPrenomSub:'Prénom',
    labelAdresse: 'Address',
    labelAdresseSub:'Adresse',
    labelEmail:   'Email',
    labelEmailSub:'Courriel',
    labelSuggestion:'Suggestion',
    labelSuggestionSub:'Suggestion',
    placeholderSuggestion:'Describe your bus route suggestion… / Décrivez votre suggestion de ligne de bus…',
    saveError:    'Could not send your information — check your connection and try again.',
  },
}

export const POSTAL_T = {
  fr: {
    title:        'Votre code postal',
    subtitle:     'Your postal code',
    instr:        'BMT est réservé aux citoyens du Grand Moncton (Moncton, Riverview, Dieppe).',
    label:        'Code postal',
    labelSub:     'Postal code',
    placeholder:  'E1A 1A1',
    required:     'Requis',
    invalidFormat:'Format invalide (ex. E1A 1A1)',
    outOfZone:    "Désolé, BMT est réservé aux résidents du Grand Moncton pour l'instant.",
    outOfZoneSub: 'Sorry, BMT is currently limited to Greater Moncton residents.',
    continue:     'Continuer / Continue',
  },
  en: {
    title:        'Your postal code',
    subtitle:     'Votre code postal',
    instr:        'BMT is limited to Greater Moncton citizens (Moncton, Riverview, Dieppe).',
    label:        'Postal code',
    labelSub:     'Code postal',
    placeholder:  'E1A 1A1',
    required:     'Required',
    invalidFormat:'Invalid format (e.g. E1A 1A1)',
    outOfZone:    'Sorry, BMT is currently limited to Greater Moncton residents.',
    outOfZoneSub: "Désolé, BMT est réservé aux résidents du Grand Moncton pour l'instant.",
    continue:     'Continue / Continuer',
  },
}

export const POSTAL_T = {
  fr: {
    title:        'Votre code postal',
    subtitle:     'Your postal code',
    instr:        'BMT est réservé aux citoyens du Grand Moncton (Moncton, Riverview, Dieppe).',
    label:        'Code postal',
    labelSub:     'Postal code',
    placeholder:  'E1A 1A1',
    required:     'Requis',
    invalidFormat:'Format invalide (ex. E1A 1A1)',
    outOfZone:    "Désolé, BMT est réservé aux résidents du Grand Moncton pour l'instant.",
    outOfZoneSub: 'Sorry, BMT is currently limited to Greater Moncton residents.',
    continue:     'Continuer / Continue',
  },
  en: {
    title:        'Your postal code',
    subtitle:     'Votre code postal',
    instr:        'BMT is limited to Greater Moncton citizens (Moncton, Riverview, Dieppe).',
    label:        'Postal code',
    labelSub:     'Code postal',
    placeholder:  'E1A 1A1',
    required:     'Required',
    invalidFormat:'Invalid format (e.g. E1A 1A1)',
    outOfZone:    'Sorry, BMT is currently limited to Greater Moncton residents.',
    outOfZoneSub: "Désolé, BMT est réservé aux résidents du Grand Moncton pour l'instant.",
    continue:     'Continue / Continuer',
  },
}

export const ADMIN_T = {
  fr: {
    // Login
    loginTitle:    'Accès Admin',
    loginInstr:    "Entrez vos identifiants pour accéder au panneau d'administration.",
    loginInstrSub: 'Enter your credentials to access the admin panel.',
    loginUser:     'Utilisateur / Username',
    loginPass:     "Code d'accès / Password",
    loginShow:     'Afficher',
    loginHide:     'Masquer',
    loginBtn:      'Se connecter / Sign in',
    loginHint:     'Accès réservé aux administrateurs BMT/CME autorisés.',
    loginHintSub:  'Access restricted to authorized BMT/CME administrators.',
    loginErrFill:  'Veuillez remplir tous les champs. / Please fill in all fields.',
    loginErrCreds: 'Identifiants invalides. / Invalid credentials.',
    // Nav
    navDash:    'Dashboard',
    navSubs:    'Soumissions',
    navMap:     'Carte mère',
    navSim:     'Simulateur',
    navFinal:   'Carte finale',
    navUsers:   'Utilisateurs',
    navLogout:  'Déconnexion',
    // Dashboard
    dashTitle:  'Tableau de bord',
    dashSub:    'Dashboard — Build Moncton Together',
    dateLocale: 'fr-CA' as string,
    // Map legend
    mapPageTitle:  'Carte de demande citoyenne — Grand Moncton',
    legendTitle:   'Intensité de demande',
    legHigh:       'Très demandé',
    legMed:        'Demandé',
    legLow:        'Peu demandé',
    legShow:       'Afficher',
    legLines:      (n: number) => `Lignes (${n})`,
    legStops:      (n: number) => `Arrêts (${n})`,
    legStations:   (n: number) => `Stations (${n})`,
    legEquity:      "Analyse d'équité",
    legEquityZones: (n: number) => `Zones d'équité (${n})`,
    eqCritical:    'Critique (écart ≥ 20)',
    eqModerate:    'Modéré (écart ≥ 10)',
    eqAdequate:    'Adéquat',
    eqSurplus:     'Surplus de service',
    eqGapVal:      (gap: number) => `Écart pondéré : ${gap > 0 ? '+' : ''}${gap} pts`,
    eqCritN:       (n: number) => `${n} critique${n > 1 ? 's' : ''}`,
    legOD:         'Matrice O-D',
    odServed:      'Desservi',
    odUnserved:    'Non desservi',
    odInfo:        (cor: number, pct: number, gaps: number) =>
      `${cor} corridors · ${pct}% couverture${gaps > 0 ? ` · ${gaps} lacunes` : ''}`,
    legODLabel:    (n: number) => `Lignes de désir (${n})`,
    legData:       'Données',
    datCitizen:    'tracés citoyens',
    datStopClus:   'clusters arrêts',
    datStaClus:    'clusters stations',
    datUpdated:    (time: string) => `Mis à jour ${time}`,
    datCorridors:  (cor: number, cells: number) => `${cor} corridors · ${cells} cellules actives`,
    btnRefresh:    '↺ Rafraîchir les données',
    // Map popups
    popCorridor:   (n: number) => `${n} citoyen${n > 1 ? 's' : ''} ont tracé ce corridor`,
    popStop:       (n: number) => `${n} citoyen${n > 1 ? 's' : ''} ont voté pour cet arrêt`,
    popStation:    (n: number) => `${n} citoyen${n > 1 ? 's' : ''} ont proposé cette station`,
    popNeed:       'Score besoin',
    popService:    'Score service',
    popGap:        'Écart',
    popPop:        'Population',
    popIncome:     'Revenu médian',
    popSeniors:    '% aînés (65+)',
    popTrips:      (trips: number, traces: number) =>
      `${trips.toLocaleString()} voy/j estimés · ${traces} tracé${traces > 1 ? 's' : ''}`,
    popServed:     '✓ Desservi',
    popUnserved:   '⚠ Non desservi',
    popODFb:       (n: number) => `${n} déplacements enregistrés`,
    // Density badge
    denHigh:       'Très demandé',
    denMed:        'Demandé',
    denLow:        'Peu demandé',
    eqLevel:       (level: string): string =>
      level === 'critical' ? 'Critique' : level === 'moderate' ? 'Modéré' :
      level === 'adequate' ? 'Adéquat' : 'Surplus',
    // Simulator
    simTitle:      'Simulateur',
    simSub:        'Impact en temps réel',
    simCoverage:   'couverture',
    simExcellent:  'Excellent',
    simAccept:     'Acceptable',
    simInsuff:     'Insuffisant',
    simGain:       '▲ Impact positif — couverture améliorée',
    simLoss:       '▼ Impact négatif — zone découverte',
    simDeadZone:   (n: number) => `${n} zone${n > 1 ? 's' : ''} morte${n > 1 ? 's' : ''}`,
    simTabSim:     'Simulation',
    simTabAch:     'Achalandage',
    simTabScen:    'Scénarios',
    simTabOD:      'O-D',
    simTabEq:      'Équité',
    simDisplay:    'Affichage',
    simCovZones:   'Zones de couverture',
    simBusLines:   'Lignes de bus',
    simDeadZones:  'Zones mortes',
    simLinesN:     (active: number, total: number) => `Lignes (${active}/${total} actives)`,
    simStopsN:     (active: number, total: number) => `Arrêts & Stations (${active}/${total} actifs)`,
    simAddStop:    '+ Ajouter arrêt',
    simCancelAdd:  '✕ Annuler',
    simReset:      '↺ Réinitialiser',
    simGenFinal:   'Générer la carte finale →',
    simClickAdd:   'Cliquez sur la carte pour placer un nouvel arrêt',
    simLoadRid:    'Calcul achalandage…',
    simLoadOD:     'Chargement O-D…',
    simLoadEq:     'Calcul équité…',
    simNewStop:    (n: number) => `Nouvel arrêt #${n}`,
    stopActivate:  'Activer',
    stopDeact:     'Désactiver',
    // Ridership tab
    ridPeakToggle: 'Heure de pointe (×2,9 h AM+PM)',
    ridPeakUnit:   'montées / heure de pointe',
    ridDayUnit:    'passagers / jour estimés',
    ridRevenue:    'Recettes billetterie',
    ridFarebox:    'Récupération tarifaire',
    ridBuses:      'Parc min. heure de pointe',
    ridBusUnit:    'autobus',
    ridByLine:     'Achalandage par ligne',
    ridAnalysis:   'Analyse : ',
    ridTopRoute:   (label: string, n: number) =>
      `${label} génère le plus de montées (${n.toLocaleString()} pass./j).`,
    ridFbWarn:     (pct: number) =>
      `La récupération tarifaire (${pct} %) est sous le seuil recommandé (20 %).`,
    ridModeSplit:  (pct: string, rev: number) => `Part modale ${pct} % · ${rev.toLocaleString()} $/j`,
    // Scenarios tab
    scenSlot:      (slot: string) => `Scénario ${slot}`,
    scenSave:      'Sauvegarder',
    scenCov:       'Couverture',
    scenPass:      'Passagers',
    scenDead:      'Zones mortes',
    scenActive:    'Arrêts actifs',
    scenEmpty:     'Aucun scénario sauvegardé',
    scenCompare:   'Comparaison',
    scenThScen:    'Scénario',
    scenThCov:     'Couv.',
    scenThPass:    'Pass./j',
    scenThDead:    'Zones⚠',
    scenCurrent:   '● En cours',
    scenNote:      'Vert = meilleur · Rouge = moins performant',
    // OD tab
    odTrips:       'voyages/j estimés',
    odWithSvc:     'avec desserte',
    odTopCor:      'Corridors les plus demandés',
    odUnmet:       'Demande non desservie',
    odAllServed:   'Excellent ! Tous les corridors prioritaires sont desservis par les lignes actives.',
    odCorTrips:    (trips: number, traces: number) =>
      `${trips.toLocaleString()} voy/j · ${traces} tracé${traces > 1 ? 's' : ''} citoyen${traces > 1 ? 's' : ''}`,
    odUnmetDet:    (traces: number) =>
      `Aucune desserte directe · ${traces} citoyen${traces > 1 ? 's' : ''} concerné${traces > 1 ? 's' : ''}`,
    // Equity tab
    eqWGap:        'écart pondéré',
    eqCritZones:   'zones critiques',
    eqAvgSvc:      'service moyen',
    eqCritWarn:    (zone: string, gap: number) => `⚠ Priorité : ${zone} (écart +${gap} pts)`,
    eqOk:          '✓ Aucune zone en déficit critique',
    eqByZone:      'Équité par zone',
    eqNeed:        'Besoin',
    eqService:     'Service',
    eqGap:         (gap: number) => `Écart : ${gap > 0 ? '+' : ''}${gap} pts`,
    eqMeta:        (income: number, seniors: number) => `rev. ${income.toLocaleString()} $ · ${seniors}% aînés`,
    // Final map
    finalTitle:    'Carte Finale',
    finalSub:      'Conforme N.-B. — Prête à adopter',
    finalLines:    'lignes',
    finalStops:    'arrêts',
    finalPass:     'pass./j',
    finalOfficial: 'Lignes officielles',
    finalCompl:    'Conformité N.-B.',
    finalBounds:   'Limites municipales',
    finalPrint:    '🖨 Imprimer / PDF',
    finalSubmit:   '⬆ Soumettre à la Ville',
    finalSubmitted:'✓ Soumis à la Ville',
    finalRouteLabel: (r: { labelFR: string; labelEN: string }) => r.labelFR.split('—')[1]?.trim() ?? '',
    finalPType:    'Type',
    finalPFreq:    'Fréquence',
    finalPRide:    'Achalandage',
    finalPStops:   'Arrêts',
    finalPLines:   'Lignes',
    finalRevision: [
      ['Document',  'BMT-CARTE-001'],
      ['Révision',  '1.0'],
      ['Date',      'Avr. 2026'],
      ['Autorité',  'Codiac Transpo'],
      ['Statut',    'Approuvé — BMT/CME'],
    ] as [string, string][],
  },
  en: {
    // Login
    loginTitle:    'Admin Access',
    loginInstr:    'Enter your credentials to access the admin panel.',
    loginInstrSub: "Entrez vos identifiants pour accéder au panneau d'administration.",
    loginUser:     'Username / Utilisateur',
    loginPass:     "Password / Code d'accès",
    loginShow:     'Show',
    loginHide:     'Hide',
    loginBtn:      'Sign in / Se connecter',
    loginHint:     'Access restricted to authorized BMT/CME administrators.',
    loginHintSub:  'Accès réservé aux administrateurs BMT/CME autorisés.',
    loginErrFill:  'Please fill in all fields. / Veuillez remplir tous les champs.',
    loginErrCreds: 'Invalid credentials. / Identifiants invalides.',
    // Nav
    navDash:    'Dashboard',
    navSubs:    'Submissions',
    navMap:     'Main map',
    navSim:     'Simulator',
    navFinal:   'Final map',
    navUsers:   'Users',
    navLogout:  'Log out',
    // Dashboard
    dashTitle:  'Dashboard',
    dashSub:    'Tableau de bord — Build Moncton Together',
    dateLocale: 'en-CA' as string,
    // Map legend
    mapPageTitle:  'Citizen demand map — Grand Moncton',
    legendTitle:   'Demand intensity',
    legHigh:       'High demand',
    legMed:        'Moderate',
    legLow:        'Low demand',
    legShow:       'Show',
    legLines:      (n: number) => `Lines (${n})`,
    legStops:      (n: number) => `Stops (${n})`,
    legStations:   (n: number) => `Stations (${n})`,
    legEquity:      'Equity analysis',
    legEquityZones: (n: number) => `Equity zones (${n})`,
    eqCritical:    'Critical (gap ≥ 20)',
    eqModerate:    'Moderate (gap ≥ 10)',
    eqAdequate:    'Adequate',
    eqSurplus:     'Service surplus',
    eqGapVal:      (gap: number) => `Weighted gap: ${gap > 0 ? '+' : ''}${gap} pts`,
    eqCritN:       (n: number) => `${n} critical`,
    legOD:         'O-D Matrix',
    odServed:      'Served',
    odUnserved:    'Unserved',
    odInfo:        (cor: number, pct: number, gaps: number) =>
      `${cor} corridors · ${pct}% coverage${gaps > 0 ? ` · ${gaps} gaps` : ''}`,
    legODLabel:    (n: number) => `Desire lines (${n})`,
    legData:       'Data',
    datCitizen:    'citizen routes',
    datStopClus:   'stop clusters',
    datStaClus:    'station clusters',
    datUpdated:    (time: string) => `Updated ${time}`,
    datCorridors:  (cor: number, cells: number) => `${cor} corridors · ${cells} active cells`,
    btnRefresh:    '↺ Refresh data',
    // Map popups
    popCorridor:   (n: number) => `${n} citizen${n > 1 ? 's' : ''} drew this corridor`,
    popStop:       (n: number) => `${n} citizen${n > 1 ? 's' : ''} voted for this stop`,
    popStation:    (n: number) => `${n} citizen${n > 1 ? 's' : ''} proposed this station`,
    popNeed:       'Need score',
    popService:    'Service score',
    popGap:        'Gap',
    popPop:        'Population',
    popIncome:     'Median income',
    popSeniors:    '% seniors (65+)',
    popTrips:      (trips: number, traces: number) =>
      `${trips.toLocaleString()} trips/day est. · ${traces} route${traces > 1 ? 's' : ''}`,
    popServed:     '✓ Served',
    popUnserved:   '⚠ Unserved',
    popODFb:       (n: number) => `${n} recorded trips`,
    // Density badge
    denHigh:       'High demand',
    denMed:        'Moderate',
    denLow:        'Low demand',
    eqLevel:       (level: string): string =>
      level === 'critical' ? 'Critical' : level === 'moderate' ? 'Moderate' :
      level === 'adequate' ? 'Adequate' : 'Surplus',
    // Simulator
    simTitle:      'Simulator',
    simSub:        'Real-time impact',
    simCoverage:   'coverage',
    simExcellent:  'Excellent',
    simAccept:     'Acceptable',
    simInsuff:     'Insufficient',
    simGain:       '▲ Positive impact — coverage improved',
    simLoss:       '▼ Negative impact — uncovered area',
    simDeadZone:   (n: number) => `${n} dead zone${n > 1 ? 's' : ''}`,
    simTabSim:     'Simulation',
    simTabAch:     'Ridership',
    simTabScen:    'Scenarios',
    simTabOD:      'O-D',
    simTabEq:      'Equity',
    simDisplay:    'Display',
    simCovZones:   'Coverage zones',
    simBusLines:   'Bus lines',
    simDeadZones:  'Dead zones',
    simLinesN:     (active: number, total: number) => `Lines (${active}/${total} active)`,
    simStopsN:     (active: number, total: number) => `Stops & Stations (${active}/${total} active)`,
    simAddStop:    '+ Add stop',
    simCancelAdd:  '✕ Cancel',
    simReset:      '↺ Reset',
    simGenFinal:   'Generate final map →',
    simClickAdd:   'Click on the map to place a new stop',
    simLoadRid:    'Computing ridership…',
    simLoadOD:     'Loading O-D…',
    simLoadEq:     'Computing equity…',
    simNewStop:    (n: number) => `New stop #${n}`,
    stopActivate:  'Activate',
    stopDeact:     'Deactivate',
    // Ridership tab
    ridPeakToggle: 'Peak hour (×2.9 h AM+PM)',
    ridPeakUnit:   'boardings / peak hour',
    ridDayUnit:    'estimated passengers / day',
    ridRevenue:    'Fare revenue',
    ridFarebox:    'Farebox recovery',
    ridBuses:      'Min. fleet at peak',
    ridBusUnit:    'buses',
    ridByLine:     'Ridership by line',
    ridAnalysis:   'Analysis: ',
    ridTopRoute:   (label: string, n: number) =>
      `${label} generates the most boardings (${n.toLocaleString()} pass./day).`,
    ridFbWarn:     (pct: number) =>
      `Farebox recovery (${pct}%) is below the recommended threshold (20%).`,
    ridModeSplit:  (pct: string, rev: number) => `Mode share ${pct}% · ${rev.toLocaleString()} $/day`,
    // Scenarios tab
    scenSlot:      (slot: string) => `Scenario ${slot}`,
    scenSave:      'Save',
    scenCov:       'Coverage',
    scenPass:      'Passengers',
    scenDead:      'Dead zones',
    scenActive:    'Active stops',
    scenEmpty:     'No scenario saved',
    scenCompare:   'Comparison',
    scenThScen:    'Scenario',
    scenThCov:     'Cov.',
    scenThPass:    'Pass./day',
    scenThDead:    'Dead⚠',
    scenCurrent:   '● Current',
    scenNote:      'Green = best · Red = worst',
    // OD tab
    odTrips:       'trips/day est.',
    odWithSvc:     'with service',
    odTopCor:      'Top demand corridors',
    odUnmet:       'Unmet demand',
    odAllServed:   'Excellent! All priority corridors are served by active lines.',
    odCorTrips:    (trips: number, traces: number) =>
      `${trips.toLocaleString()} trips/day · ${traces} citizen route${traces > 1 ? 's' : ''}`,
    odUnmetDet:    (traces: number) =>
      `No direct service · ${traces} citizen${traces > 1 ? 's' : ''} affected`,
    // Equity tab
    eqWGap:        'weighted gap',
    eqCritZones:   'critical zones',
    eqAvgSvc:      'avg. service',
    eqCritWarn:    (zone: string, gap: number) => `⚠ Priority: ${zone} (gap +${gap} pts)`,
    eqOk:          '✓ No zone in critical deficit',
    eqByZone:      'Equity by zone',
    eqNeed:        'Need',
    eqService:     'Service',
    eqGap:         (gap: number) => `Gap: ${gap > 0 ? '+' : ''}${gap} pts`,
    eqMeta:        (income: number, seniors: number) => `income ${income.toLocaleString()} $ · ${seniors}% seniors`,
    // Final map
    finalTitle:    'Final Map',
    finalSub:      'N.B. Compliant — Ready to adopt',
    finalLines:    'lines',
    finalStops:    'stops',
    finalPass:     'pass./day',
    finalOfficial: 'Official lines',
    finalCompl:    'N.B. Compliance',
    finalBounds:   'Municipal boundaries',
    finalPrint:    '🖨 Print / PDF',
    finalSubmit:   '⬆ Submit to City',
    finalSubmitted:'✓ Submitted to City',
    finalRouteLabel: (r: { labelFR: string; labelEN: string }) => r.labelEN.split('—')[1]?.trim() ?? '',
    finalPType:    'Type',
    finalPFreq:    'Frequency',
    finalPRide:    'Ridership',
    finalPStops:   'Stops',
    finalPLines:   'Lines',
    finalRevision: [
      ['Document',  'BMT-CARTE-001'],
      ['Revision',  '1.0'],
      ['Date',      'Apr. 2026'],
      ['Authority', 'Codiac Transpo'],
      ['Status',    'Approved — BMT/CME'],
    ] as [string, string][],
  },
}
